### ISSUE TITLE
BUG: Search in the documentation is broken

### ISSUE THREAD

**Issue by mherde** [scikit-activeml/scikit-activeml#370]
### Describe the issue:

No results are shown when searching in the documentation: https://scikit-activeml.github.io/scikit-activeml-docs/

### Reproduce the bug via a code example:
Type in `active` in the search bar of the documentation. No results will be shown.

### Error message:
```
Uncaught TypeError: $.getQueryParameters is not a function
    at Object.highlightSearchWords (doctools.js:225:20)
    at Object.init (doctools.js:155:10)
    at HTMLDocument.<anonymous> (doctools.js:322:17)
    at e (jquery.js:2:30005)
    at t (jquery.js:2:30307)
```

**Comment by mherde** [comment]
Close (cf. #421)
